name: package-deploy

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches: 
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://nuget.pkg.github.com/MikyM/index.json
        dotnet-version: 6.0.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Check out Code 
      uses: actions/checkout@v2
    - name: Add DSharpPlus nightly feed
      run: dotnet nuget add source https://nuget.emzi0767.com/api/v3/index.json -n dsharp
    - name: Restore dependencies
      run: dotnet restore
    - name: Build solution and generate NuGet package
      run: |  
        cd MikyM.Discord
        dotnet pack -c Release -o out 
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./MikyM.Discord/out/*.nupkg --skip-duplicate --no-symbols true
    - name: Push generated package to NuGet registry
      run: dotnet nuget push ./MikyM.Discord/out/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json